#!/bin/bash
#
# Copyright (C) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -e

cleanup() {
    if [ -d $DIR.bootstrap ]; then
        rm -rf $DIR.bootstrap
    fi
}

VIRT=

if [ -r /etc/dci-openshift-agent/config ]; then
    . /etc/dci-openshift-agent/config
fi

BASEDIR=$(cd $(dirname $0); pwd)

if [ $# = 0 -o "$1" = -h ]; then
  name=$(basename -- "$0")
    cat << EOF
    echo "Usage: $name [--virt|--sno] [-f] (<GitHub PR URL>|<Gerrit review id>)" 1>&2
    arguments:
    --virt       Use OCP on Libvirt.
    --sno        Use SNO on Libvirt.
    -f           Force a suffix to be added.
EOF
    exit 1
fi

if [ ! -x $BASEDIR/extract-dependencies ]; then
    BASEDIR=/usr/share/dci-openshift-agent
fi

set -x

ARGS="$@"

SUFFIX=-$(echo "$@"|md5sum|cut -f1|cut -f1 -d ' ')

if [ $1 = --virt ]; then
    VIRT=--virt
    shift
elif [ $1 = --sno ]; then
    VIRT=--sno
    shift
fi

# force a suffix to be added on -f
if [ "$1" = "-f" ]; then
    # manage recursive call (bootstrap): extract the directory name
    # from the path of the command
    if grep -Fq '.bootstrap' <<< $BASEDIR; then
        SUFFIX=
        DIR=$(dirname $(dirname $BASEDIR))
        DIR=$(sed -e 's/\.bootstrap//' <<< $DIR)
    else
        SUFFIX=-$SUFFIX-$$
    fi
    CHANGEID=$2
    shift 2
else
    DIR=
    CHANGEID=$1
    shift
fi

case $CHANGEID in
    https://*)
        PR=$(sed -e 's@.*github.com/.*/\([^/]*\)/pull/\([0-9]*\)@\1-pr\2@' <<< $CHANGEID)
        if [ -z "$PR" ]; then
            echo "Unable to extract PR from $CHANGEID" 1>&2
            exit 1
        fi
        [ -n "$DIR" ] || DIR=$HOME/github/$PR$SUFFIX
        TYPE=github
        ;;
    *)
        [ -n "$DIR" ] || DIR=$HOME/gerrit/$CHANGEID$SUFFIX
        TYPE=gerrit
        ;;
esac

if [ -d $DIR ]; then
    if [ -n "$DCI_QUEUE" ] && type -p dci-queue >& /dev/null; then
         jobid="$(dci-queue searchdir $DCI_QUEUE $DIR || :)"
         if [ -z "$jobid" ]; then
             $BASEDIR/send-feedback $DIR "A job is already scheduled or running in $DIR (unable to find job id). Aborting."
             exit
         fi
         dci-queue unschedule $DCI_QUEUE $jobid
         if [ -d $DIR ]; then
             find $DIR -type d -not -perm -u=w -exec chmod u+w {} \;
             rm -rf $DIR
         fi        
    else
        $BASEDIR/send-feedback $DIR "A job is already scheduled or running in $DIR. Aborting."
        exit 1
    fi
fi

trap cleanup 0

mkdir -p $DIR
cd $DIR

echo "Depends-On: $CHANGEID" | $BASEDIR/extract-dependencies $DIR

# rerun check from the local repo
if [ -d dci-openshift-agent ]; then
    if [ $0 != $DIR.bootstrap/dci-openshift-agent/$(basename $0) ]; then
        echo "re-exec"
        cd
        mv $DIR $DIR.bootstrap
        exec $DIR.bootstrap/dci-openshift-agent/$(basename $0) $ARGS
    fi
fi

BASEDIR=$(sed -e 's/\.bootstrap//' <<< $BASEDIR)

if [ "$TYPE" = "github" ]; then
    mv *.json github.json
fi

# we should have only one directory and one or zero json file
(
  # extract depends-on from a pr body
  jq -r .body *.json || :
  # extract depends-on from the last commit message
  cd $(ls|fgrep -v .json); git log -1
) | tr -d '\r' | sort -u | $BASEDIR/extract-dependencies $DIR

# take test-runner from the local dir
if [ -d dci-openshift-agent ]; then
    BASEDIR=$PWD/dci-openshift-agent
else
    BASEDIR=/usr/share/dci-openshift-agent
fi

if [ -n "$DCI_QUEUE" ] && type -p dci-queue >& /dev/null; then
    if [ -n "$USE_PREFIX" ]; then
        dci-queue schedule $DCI_QUEUE -- $BASEDIR/test-runner $VIRT $DIR -p @RESOURCE "$@"
    else
        dci-queue schedule $DCI_QUEUE -- bash -c "echo @RESOURCE; exec $BASEDIR/test-runner $VIRT $DIR $@"
    fi
else
    $BASEDIR/test-runner $VIRT $DIR "$@"
fi

# dci-check-change ends here
