---
# Initial step
- hosts: localhost
  tags:
    - job
  tasks:
    - name: Read credentials from env vars
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

    # Schedule a new job only if not passed via pipeline
    - name: Schedule a new job
      dci_job:
        components: "{{ dci_components }}"
        components_by_query: "{{ dci_components_by_query }}"
        topic: "{{ dci_topic }}"
      register: job_info
      when: job_info is not defined

    - name: set job id
      set_fact:
        job_id: '{{ job_info.job.id }}'

    - name: 'Set DCI tags for the current job'
      dci_job:
        id: '{{ job_id }}'
        tags: '{{ dci_tags }}'
      when: dci_tags

# Step 1 : state "New job"
- name: Prepare host
  hosts: localhost
  vars:
    dci_status: 'new'
  tags:
    - configure
  tasks:
    - block:
        # Prepare host
        - name: Configure jumpbox
          include_tasks: plays/configure.yml

        # Download Openshift from DCI
        - name: Import Openshift files from DCI
          include_tasks: plays/fetch_bits.yml
      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 2 : state "Pre-run"
- name: 'Launch pre-run to deploy installer'
  hosts: localhost
  tags:
    - pre-run
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        # Deploy infrastructure
        - name: Run the pre-run hook
          include_tasks: '{{ dci_config_dir }}/hooks/pre-run.yml'

      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 3 : state "configure"
- name: 'Launch configure'
  hosts: provisioner
  tags:
    - running
    - configure
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - name: Launch configure
          include_tasks: '{{ dci_config_dir }}/hooks/configure.yml'

      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 4 : state "installing"
- name: 'Launch install'
  hosts: provisioner
  tags:
    - running
    - installing
  vars:
    dci_status: 'running'
  tasks:
    - block:
        # Launch installer
        - name: Launch installer
          include_tasks: '{{ dci_config_dir }}/hooks/running.yml'

      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 5 : state "redhat-testing"
- name: 'Launch Red Hat tests'
  hosts: localhost
  tags:
    - running
    - testing
    - redhat-testing
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - name: Login to the openshift cluster
          include_tasks: plays/oc-setup.yml

        - name: Setup podman on the jumphost
          include_tasks: plays/podman-setup.yml

#        - name: Side-load images prior to testing
#          include_tasks: plays/image-side-load.yml

#        - name: Run the Red Hat tests
#          include_tasks: plays/dci-tests.yml
#          when: dci_openshift_agent_conformance is defined and dci_openshift_agent_conformance != ""

         # Setup and run cnf-tests
        - name: Create local git repo on jumphost for disconnected cnf-tests
          include_tasks: plays/create_local_git_repo.yaml

        - name: Mirror images to local registry for disconnected cnf-tests
          include_tasks: plays/mirror_images.yml
          when: dci_openshift_agent_cnf_tests_mode is defined and dci_openshift_agent_cnf_tests_mode == "offline"

        - name: Deploy cnf features
          include_tasks: plays/cnf-tests-setup.yaml
          when: (dci_openshift_agent_cnf_tests_mode is defined) and (dci_openshift_agent_cnf_tests_mode == "online" or dci_openshift_agent_cnf_tests_mode == "offline")

        - name: Run cnf tests
          include_tasks: plays/cnf-tests-run.yaml
          when: (dci_openshift_agent_cnf_tests_mode is defined) and (dci_openshift_agent_cnf_tests_mode == "online" or dci_openshift_agent_cnf_tests_mode == "offline")

      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml
      always:
        - name: Clean up clusterconfig dir
          include_tasks: plays/cleanup.yml

# Step 6 : state "partner-testing"
- name: 'Launch partner tests'
  hosts: localhost
  tags:
    - running
    - testing
    - partner-testing
  vars:
    dci_status: 'running'
  tasks:
    - block:
        # Launch user tests
        - name: Run the partner tests hook
          include_tasks: '{{ dci_config_dir }}/hooks/user-tests.yml'

      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 7 : Upload logs
- name: Upload logs to DCI Control server
  hosts: localhost
  tags:
    - post-run
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: plays/upload_logs.yml
      rescue:
        - name: Run the teardown process
          include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
          when: dci_teardown_on_failure|bool

        - name: Run the failure process
          include_tasks: plays/failure.yml

# Step 8 : state "success"
- name: 'Success'
  hosts: localhost
  tags:
    - success
  vars:
    dci_status: 'success'
  tasks:
    - name: Run the post-run hook
      include_tasks: '{{ dci_config_dir }}/hooks/success.yml'

    - name: Run the teardown process
      include_tasks: "{{ dci_config_dir }}/hooks/teardown.yml"
      when: dci_teardown_on_failure|bool
