#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
start=0
params="$(getopt -o hsdp:c:v -l help,start,dev,prefix:,config:,verbose --name "$(basename -- "$0")" -- "$@")"

function usage ()
{
    name=$(basename -- "$0")
    cat << EOF
Usage: $name [-h] [-s] [-d] [-v] [-p PREFIX] [-c CONFIG] -- [ansible-playbook args]

arguments:
    -h, --help        Display this help message.
    -s, --start       Start the dci-openshift-agent.
    -p PREFIX, --prefix PREFIX
                      Specify prefix for Inventory and settings (use to specify different
                      clusters for example)
    -d, --dev         Use script directory to find dcirc.sh and dci-openshift-agent.yml (for dev usage)
    -c CONFIG, --config CONFIG
                      Path to config file. default is /etc/dci-openshift-agent/settings.yml
    -v, --verbose     Display commands
EOF
    exit $1
}

if [ -r /etc/dci-openshift-agent/config ]; then
    . /etc/dci-openshift-agent/config
fi

config_dir=${CONFIG_DIR:-/etc/dci-openshift-agent}
config=$config_dir/settings.yml

eval set -- "$params"
unset params

while true
do
    case $1 in
        -h|--help)
            usage 0
        ;;
        -s|--start)
            start=1
            shift
        ;;
        -d|--dev)
            dev=1
            shift
        ;;
        -c|--config)
            shift
            config=$1
            shift
        ;;
        -p|--prefix)
            shift
            prefix=$1
            shift
        ;;
        -v|--verbose)
            set -x
            shift
            ;;
        --)
            shift
            break
        ;;
        *)
            usage 1
        ;;
    esac
done

if [ "$( id -u dci-openshift-agent )" != "$( id -u )" ]; then
    echo "must be run as the dci-openshift-agent user"
    usage 1
fi

if [ -n "$prefix" ]; then
    hosts="$config_dir/${prefix}-hosts"
    settings="$config_dir/${prefix}-settings.yml"
    if [ -e "$settings" ]; then
        prefix_args="${prefix_args} -e @$settings"
    else
        echo "Missing $settings, will only use $config."
    fi

    if [ -e "$hosts" ]; then
        prefix_args="-i $hosts"
    else
        echo "Missing $hosts"
        exit 1
    fi
fi

if [ "$start" -eq 1 ]; then
    if [ -z "$dev" ]; then
        [ -e /etc/dci-openshift-agent/dcirc.sh ] && . /etc/dci-openshift-agent/dcirc.sh
        [ -d ${DCI_OPENSHIFT_AGENT_DIR:-/usr/share/dci-openshift-agent} ] && cd ${DCI_OPENSHIFT_AGENT_DIR:-/usr/share/dci-openshift-agent}
    else
        [ -e $DIR/dcirc.sh ] && . $DIR/dcirc.sh
        export ANSIBLE_CONFIG=$DIR/dev-ansible.cfg
    fi
    exec ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} "$@"
else
    echo "Dry-Run: pass -s or --start to actually execute"
    if [ -z "$dev" ]; then
        echo ". /etc/dci-openshift-agent/dcirc.sh"
        echo "cd /usr/share/dci-openshift-agent"
    else
        echo "$DIR/dcirc.sh"
        echo "ANSIBLE_CONFIG=$DIR/dev-ansible.cfg"
    fi
    echo ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} "$@"
    exit 1
fi
