---

roles:
  - src: https://softwarefactory-project.io/r/ansible-role-dci-podman
    scm: git

collections:
  - name: kubernetes.core
    version: 2.4.2
  - name: containers.podman
  - name: community.general
    version: 7.0.1
  - name: community.libvirt
  - name: ansible.posix
  - name: redhatci.ocp
