---

roles:
  - src: https://softwarefactory-project.io/r/ansible-role-dci-sync-registry
    scm: git
  - src: https://softwarefactory-project.io/r/ansible-role-dci-podman
    scm: git

collections:
  - name: community.kubernetes
  - name: containers.podman
  - name: community.general
  - name: community.libvirt
  - name: ansible.posix
