#!/bin/bash
#
# Copyright (C) 2021-2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -x

DIR="$1"
BODY="$2"
TAG="$3"
VOTE="$4"

[ -z "$DO_VOTE" ] && VOTE=0

GERRIT_JSON='{"message":"'${BODY}'"}'

if [ -n "${TAG}" ]; then
    GERRIT_JSON=$( echo ${GERRIT_JSON} |
                jq '. += {"tag": "'${TAG}'"}' )
fi

if [ -n "${VOTE}" ]; then
    GERRIT_JSON=$( echo ${GERRIT_JSON} |
                jq '. += {"labels": {"verified": "'${VOTE}'"}}' )
fi

for json in $(ls $DIR/*.json); do
    # gerrit
    if [ $(jq -r .url $json) = null ]; then
        if [ -z "$GERRIT_SSH_ID" ] || [ -z "$GERRIT_USER" ]; then
            continue
        fi
        CHANGEID=$(jq -r ._number $json)
        CURREV=$(jq -r .current_revision $json)
        PATCHSET=$(jq -r ".revisions[\"$CURREV\"]._number" $json)
        echo "${GERRIT_JSON}" |
            ssh \
            -i ~/.ssh/"$GERRIT_SSH_ID" \
            -p 29418 \
            $GERRIT_USER \
            gerrit review -j $CHANGEID,$PATCHSET
    # github
    else
        ISSUE_URL=$(jq -r .issue_url $json)
        if [ -r ~/.github_token ]; then
            curl -s -H "Authorization: token $(cat ~/.github_token)" -X POST -d "{\"body\": \"$BODY\"}" "$ISSUE_URL/comments"
        fi
    fi
done

# send-feedback ends here
