---
- name: Create hosts inventory file
  import_playbook: parse-template.yml

- name: Create directories
  hosts: provisioner
  tasks:
    - name: Create cache_dir_base Directory
      become: true
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'
      loop:
        - "{{ cache_dir_base }}"
        - "{{ registry_dir }}"
        - "{{ vm_create_scripts_dir }}"
        - "{{ sushy_dir }}"
        - "{{ http_dir }}"
        - "{{ iso_download_dest_path }}"
        - "{{ rootfs_directory }}"
