#!/bin/sh
#
# Copyright (C) 2020 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

log=$1
dir="$2"

if [ $# -lt 3 ]; then
    echo "Usage: $0 <provisioner login> <dest dir> <masters name>" 1>&2
    exit 1
fi

rem="timeout -v 20m ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log"

shift 2
masters=()
for name in "$@"; do
      mod=$(echo "$name" | tr -d ,][)
      masters+=($mod)
done

# Get IP from Bootstrap VM if it's running
vm=$(LANG=en_US.UTF-8 $rem sudo virsh list | awk '/.*-bootstrap\s+running/ {print $2}')
ip=$($rem sudo virsh domifaddr --source arp $vm 2>/dev/null | grep -m1 -oP '(\d{1,3}\.){3}\d{1,3}')

set -x

domain=$($rem hostname -d)

# Copy openshift install log and rendered install config
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log:clusterconfigs/.openshift_install.log $dir/openshift_install.log
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log:clusterconfigs/install-config.yaml.bkup $dir/install-config-yaml.txt

if [ -n "$ip" ]; then
    echo "found VM IPv4 $ip"

    #Installer logs
    for master in "${masters[@]}"; do
      master_param+=" --master $master.$domain"
    done
    # dump an archive with bootstrap logs
    $rem openshift-baremetal-install gather bootstrap --dir=/tmp/gatherBootstrap --bootstrap $ip $master_param
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log:/tmp/gatherBootstrap/* $dir/
    $rem rm -rf /tmp/gatherBootstrap
    core="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR core@$ip"

    for serv in release-image bootkube; do
        $rem $core journalctl -b -u $serv.service > $dir/$serv.log
    done

    # dnsmasq, httpd, ironic-api, ironic-conductor, ironic-inspector real logs are only retrieved when saving the standard error output, then we save both
    for pod in $($rem $core sudo podman ps 2>&1 | sed 's/.* //'|egrep -v '^(hosts\.|NAMES$)'); do
            $rem $core sudo podman logs $pod >> $dir/$pod.log 2>&1
    done

    # If API lists nodes then SSH to them and get the journal logs
    nodes=$(oc get nodes -o custom-columns=NAME:.metadata.name --no-headers 2>/dev/null | wc -l)
    if [ "$nodes" -gt 0 ]; then

      # Get nodes journals and outputs
      for h in $($rem oc get nodes -o custom-columns=NAME:.metadata.name --no-headers -l node-role.kubernetes.io/master= 2>/dev/null); do
        # Journal logs
        $rem ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR \
          core@$h.$domain sudo journalctl --all > $dir/journal-$h.log
      done

      # Get the output of various oc commands
      $rem oc get nodes > $dir/nodes.txt
      $rem oc get csr > $dir/csr.txt
      $rem oc get clusteroperator > $dir/clusteroperator.txt
    else
      # Get only journals of master nodes
      for h in ${masters[@]}; do
        nodename=$(echo $h | xargs)
        $rem ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR \
          core@$h sudo journalctl --all > $dir/journal-${nodename%%.*}.log
      done
    fi

else
    remdir=$($rem mktemp -d)

    # Get nodes journals and outputs
    if [ -n "$remdir" ]; then
        for h in $($rem oc get nodes|tail -n +2|awk '{print $1;}'); do
          # Journal logs
            $rem ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR \
              core@$h.$domain sudo journalctl --all > $dir/journal-$h.log
        done

        # Ironic logs
        metal3_pod=$($rem oc \
                        -n openshift-machine-api \
                        get pods \
                        -l baremetal.openshift.io/cluster-baremetal-operator=metal3-state \
                        -o jsonpath='{.items[0].metadata.name}' )
        if [ -n "$metal3_pod" ]; then
            echo "Downloading ironic logs from $metal3_pod"
            $rem oc cp openshift-machine-api/$metal3_pod:/var/log/ironic/. $remdir -c metal3-ironic-conductor
        fi

        # Get the output of various oc commands
        $rem oc version > $dir/version.txt
        $rem oc get clusterversion/version > $dir/clusterversion.txt
        $rem oc get clusteroperator > $dir/clusteroperator.txt
        $rem oc get network cluster -o yaml > $dir/clusternetwork.yaml
        $rem oc get nodes -o wide > $dir/nodes.txt
        $rem oc get nodes -o yaml > $dir/all-nodes.yaml
        $rem oc get events --all-namespaces --sort-by='.metadata.creationTimestamp' > $dir/events.txt
        $rem oc get pods --all-namespaces -o wide > $dir/pods.txt

        # must-gather
        # When a policy is defined, use the same mirror (local registry)
        registry=$($rem oc get imageContentSourcePolicy image-policy-0 -o json 2>/dev/null |
                            jq -r '.spec.repositoryDigestMirrors[].mirrors[]' |
                            grep -Pom1 '(\w+[.:])+\d+')
        for image in ${DCI_MUST_GATHER_IMAGES:-"registry.redhat.io/openshift4/ose-must-gather"}
        do
            if [[ -n "${registry}" ]]
            then
                image="${registry}/${image#*/}"
            fi

            must_gather_opts="${must_gather_opts} --image=${image}"
        done

        must_gather_dir="${remdir}/must_gather"
        $rem mkdir "${must_gather_dir}"
        $rem oc adm must-gather \
             --dest-dir=${must_gather_dir} \
             ${must_gather_opts}

        # Compress must-gather data, using a friendly name
        $rem tar \
            --use-compress-program='"pigz --best --recursive"' \
            --directory "${remdir}" \
            --create \
            --file ${must_gather_dir}.tar.gz must_gather/
        $rem rm -rf "${must_gather_dir}"

        # Get remote logs
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log:$remdir/* $dir/
        $rem rm -rf $remdir

        # Post processing
        cd $dir
        for f in $(ls *.tar.gz 2> /dev/null); do
            if grep -q journal <<<$(tar tzf $f); then
                hostname=$(tar xOf $f journal|grep 'set hostname'|sed -e "s/.*set hostname to '//" -e "s/'.*//")
                if [ -n "$hostname" ]; then
                    mv $f $hostname-files.tar.gz
                fi
            fi
        done
    else
        echo "Unable to create a temporary directory on $rem" 1>&2
    fi
fi

# get-logs ends here
