#!/bin/bash
#
# Copyright (C) 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -xe

csv_file=${1}
registry=${2:-quay.io}
org=${3:-openshift}

function get_digest() {
    image=$1
    digest=$(skopeo inspect docker://${image} |
        jq -r .Digest
    )
    echo ${digest}
}

csv_version=$(awk '/^  version:/ {print $NF}' "${csv_file}")
tag=$(grep -Po '^\d+\.\d+' <<<"${csv_version}")
images=(
    $(grep -Po "${registry}/${org}/\S+:${tag}" ${csv_file})
)
main_imgs=(
    $(grep "image:" ${csv_file} | grep -Po "${registry}/${org}/\S+")
)
images+=( ${main_imgs[@]})

related_images=()
for image in ${images[@]}; do
    digest=$(get_digest ${image})
    img=${image/:${tag}}
    name=${img##*/}
    img_dgst="${img}@${digest}"
    sed -i -e "s,${image},${img_dgst}," ${csv_file}
    related_images+=( "${name},${img_dgst}" )
done

if ! grep -q relatedImages "${csv_file}"; then
    tmp=$(mktemp)
    echo "  relatedImages:" >> "${tmp}"
    for ri in ${related_images[@]}; do
        name=${ri/,*}
        image=${ri/*,}
        echo "    - name: ${name}" >> "${tmp}"
        echo "      image: ${image}   # ${tag}" >> "${tmp}"
    done

    cat "${tmp}" >> "${csv_file}"
    rm -f "${tmp}"
fi
