---
- name: "Deploy a ZTP spoke cluster"
  ansible.builtin.include_tasks:
    file: acm-ztp-spoke.yml
  when:
    - acm_cluster_type == 'ztp-spoke'
    - not (dci_disconnected | default(false) | bool)

- name: "Deploy an SNO node via ACM"
  vars:
    acm_ocp_version: "{{ hostvars.localhost.version }}"
    acm_release_image: "{{ hostvars.localhost.acm_release_image }}"
    acm_force_deploy: "{{ hostvars.localhost.acm_force_deploy }}"
    acm_cluster_name: "{{ hostvars.localhost.acm_cluster_name }}"
    acm_base_domain: "{{ hostvars.localhost.acm_base_domain }}"
    acm_bmc_address: "{{ hostvars.localhost.acm_bmc_address }}"
    acm_boot_mac_address: "{{ hostvars.localhost.acm_boot_mac_address }}"
    acm_machine_cidr: "{{ hostvars.localhost.acm_machine_cidr }}"
    acm_bmc_user: "{{ hostvars.localhost.acm_bmc_user }}"
    acm_bmc_pass: "{{ hostvars.localhost.acm_bmc_pass }}"
    acm_iso_url: "{{ hostvars.localhost.acm_metal_iso_location }}"
    acm_root_fs_url: "{{ hostvars.localhost.acm_rootfs_url }}"
    acm_disconnected: "{{ dci_disconnected | default(False) | bool }}"
    acm_user_registry: "{{ acm_registries }}"
  include_role:
    name: redhatci.ocp.acm_sno
    apply:
      environment:
        - KUBECONFIG: "{{ hostvars.localhost.hub_kubeconfig_path }}"
  when:
    - acm_cluster_type == 'sno'


- name: "Deploy a MetalLB and Hypershift cluster via ACM"
  block:
    - name: "Setup MetalLB in L2 mode"
      include_role:
        name: redhatci.ocp.metallb_setup
      vars:
        mlb_ipaddr_pool:
          - "{{ metallb_ipaddr_pool_l2 }}"
      when:
        - metallb_ipaddr_pool_l2 | default('') | length

    - name: "Deploy a Hypershift cluster via ACM"
      vars:
        ah_pullsecret_file: "{{ dci_pullsecret_file }}"
      include_role:
        name: redhatci.ocp.acm_hypershift
        apply:
          environment:
            - KUBECONFIG: "{{ hostvars.localhost.hub_kubeconfig_path }}"
  when:
    - acm_cluster_type == 'hypershift'
    - not (dci_disconnected | default(false) | bool)

- name: "Save the {{ acm_cluster_type }} kubeconfig"
  copy:
    content: "{{ acm_kubeconfig_text }}"
    dest: "{{ dci_cluster_configs_dir }}/kubeconfig"
    mode: '0600'

- name: "Save {{ acm_cluster_type }} credentials"
  copy:
    content: "{{ acm_cluster_type }} credentials\n
              ---\n
              username: {{ acm_kubeconfig_user }}\n
              password: {{ acm_kubeconfig_pass }}\n"
    dest: "{{ dci_cluster_configs_dir }}/kubeadmin-password"
    mode: '0600'
  no_log: true
...
