---
- name: "Get cluster install-config"
  community.kubernetes.k8s_info:
    api: v1
    kind: ConfigMap
    name: cluster-config-v1
    namespace: kube-system
  register: ic
  until: "'resources' in ic and ic.resources != []"
  retries: 12
  delay: 5
  no_log: true

- name: "Add additional Registry CAs for Image Service"
  vars:
    install_conf: "{{ ic.resources[0].data['install-config'] | from_yaml }}"
    additional_ca: "{{ install_conf | json_query('additionalTrustBundle') }}"
  ansible.builtin.include_tasks: add-additional-ca.yml
  when:
    - dci_disconnected | default(false) | bool
    - install_type not in ['assisted']
    - dci_local_registry is defined
    - additional_ca | default("")| length > 0

- name: "Add additional Registry CAs for Image Service - ABI"
  vars:
    additional_ca: "{{ mirror_certificate }}"
  ansible.builtin.include_tasks: add-additional-ca.yml
  when:
    - dci_disconnected | default(false) | bool
    - install_type in ['assisted']
    - dci_local_registry is defined
    - mirror_certificate | default("")| length > 0

- name: "Save the install-config"
  vars:
    install_config: '{{ ic.resources[0].data["install-config"] }}'
  copy:
    content: "{{ install_config }}"
    dest: "{{ dci_cluster_configs_dir }}/cluster-install-config.yml"
    mode: 0600

- name: "Upload cluster's files to DCI Control Server"
  environment:
    - DCI_CLIENT_ID: "{{ dci_client_id }}"
    - DCI_API_SECRET: "{{ dci_api_secret }}"
    - DCI_CS_URL: "{{ dci_cs_url }}"
  dci_file:
    path: "{{ item }}"
    name: "{{ item | basename }}"
    job_id: "{{ job_id }}"
    mime: "text/plain"
  loop:
    - "{{ dci_cluster_configs_dir }}/kubeconfig"
    - "{{ dci_cluster_configs_dir }}/kubeadmin-password"
    - "{{ dci_cluster_configs_dir }}/cluster-install-config.yml"

- name: "Check if all cluster-operators are running correctly"
  community.kubernetes.k8s_info:
    kind: ClusterOperator
  register: clusteroperator_info
  vars:
    status_query: "resources[*].status.conditions[?type=='Available'].status"
    cluster_operators_available: "{{ clusteroperator_info | json_query(status_query) | flatten | unique }}"
  retries: 6
  delay: 10
  until: cluster_operators_available == ['True']
  when:
    - acm_cluster_type | default('') != 'hypershift'

- name: "Check all nodes have been provisioned"
  vars:
    install_config: "{{ ic.resources[0].data['install-config'] | from_yaml }}"
    requested_compute: "{{ install_config | json_query('compute[? name==`worker` ].replicas') | first }}"
    query: "resources[*].status.provisioning.state"
    bmh_states: >
      {% for s in bmh_info | json_query(query) | unique %}
        {{ s.split() | last }}
      {% endfor %}
    bmh_unique_states: "{{ bmh_states.split() | unique }}"
  community.kubernetes.k8s_info:
    kind: BareMetalHost
    api: metal3.io/v1alpha1
    namespace: openshift-machine-api
  register: bmh_info
  retries: "{{ (requested_compute | int + 1) * 10 }}"
  delay: 30
  until: bmh_unique_states == ['provisioned']
  when:
    - install_type in ['ipi', 'upi']

- name: "Check control plane nodes matches requested"
  vars:
    control_nodes_count: "{{ control_nodes.resources | length }}"
    install_config: "{{ ic.resources[0].data['install-config'] | from_yaml }}"
    requested_control: "{{ install_config | json_query('controlPlane.replicas') }}"
  community.kubernetes.k8s_info:
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/master"
  register: control_nodes
  retries: "{{ (requested_control | int + 1) * 10 }}"
  no_log: true
  delay: 10
  until:
    - ( control_nodes_count | int ) == ( requested_control | int )
  when:
    - acm_cluster_type | default('') != 'hypershift'

- name: "Check compute plane nodes matches requested"
  vars:
    compute_nodes_count: "{{ compute_nodes.resources | length }}"
    install_config: "{{ ic.resources[0].data['install-config'] | from_yaml }}"
    requested_compute: "{{ install_config | json_query('compute[? name==`worker` ].replicas') | first }}"
  community.kubernetes.k8s_info:
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker"
  register: compute_nodes
  no_log: true
  retries: "{{ (requested_compute | int + 1) * 10 }}"
  delay: 20
  until:
    - ( compute_nodes_count | int ) >= ( requested_compute | int )
  when:
    - acm_cluster_type | default('') not in ['hypershift', 'sno']

- name: "Create a DCI component for the rhcos_kernel"
  block:
    - name: "Create component with the rhcos kernel in use"
      vars:
        - kernel_version: "{{ control_nodes.resources[0].status.nodeInfo.kernelVersion }}"
      environment:
        - DCI_CLIENT_ID: "{{ dci_client_id }}"
        - DCI_API_SECRET: "{{ dci_api_secret }}"
        - DCI_CS_URL: "{{ dci_cs_url }}"
      dci_component:
        display_name: "rhcos_kernel {{ kernel_version }}"
        version: "{{ kernel_version }}"
        team_id: "{{ job_info['job']['team_id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        type: kernel
        state: present
      register: kernel_component

    - name: "Attach kernel component to the job"
      dci_job_component:
        component_id: "{{ kernel_component.component.id }}"
        job_id: "{{ job_id }}"
      register: job_component_result
      until: job_component_result is not failed
      retries: 5
      delay: 20
      when:
        - "'component' in kernel_component"
        - "'id' in kernel_component.component"
  ignore_errors: true

- name: "Patch clusterversion update channel"
  vars:
    base_version: "{{ version.split('.')[0] }}.{{ version.split('.')[1] }}"
  community.kubernetes.k8s:
    state: present
    name: version
    definition:
      kind: ClusterVersion
      spec:
        channel: "{{ dci_ocp_channel | default('fast') }}-{{ base_version }}"
  retries: 6
  delay: 10
  when:
    - acm_cluster_type | default('') != 'hypershift'

- block:
    - name: "Merge all inventory hosts"
      set_fact:
        all_hosts: "{{ all_hosts | default([]) + groups[item] }}"
      loop: "{{ groups.keys() | list }}"

    - name: "Apply node labels"
      include_role:
        name: redhatci.ocp.label_nodes
      vars:
        hosts_list: "{{ all_hosts | list | unique }}"
  when:
    - install_type in ['ipi', 'upi', 'sno']

- name: "Disable provisioning"
  block:
    - name: "Get provisioning"
      community.kubernetes.k8s_info:
        api_version: metal3.io/v1alpha1
        kind: Provisioning
        name: provisioning-configuration
      register: provisioning_cr

    - name: Disable provisioning
      community.kubernetes.k8s:
        definition:
          apiVersion: metal3.io/v1alpha1
          kind: Provisioning
          metadata:
            name: provisioning-configuration
          spec:
            provisioningNetwork: Disabled
      when:
        - provisioning_cr.resources | length
  when:
    - dci_disable_provisioning | default(false) | bool
    - acm_cluster_type | default('') != 'hypershift'

- name: "Setup additional credentials to OCP"
  vars:
    os_config_dir: "{{ dci_cluster_configs_dir }}"
  include_role:
    name: redhatci.ocp.oc_setup

- name: "Upload additional credentials to DCI Control Server"
  environment:
    - DCI_CLIENT_ID: "{{ dci_client_id }}"
    - DCI_API_SECRET: "{{ dci_api_secret }}"
    - DCI_CS_URL: "{{ dci_cs_url }}"
  dci_file:
    path: "{{ item }}"
    name: "{{ item | basename }}"
    job_id: "{{ job_id }}"
    mime: "text/plain"
  loop:
    - "{{ dci_cluster_configs_dir }}/ocp_creds.txt"

- name: Set override fact for ACM hubs
  set_fact:
    hub_os_images:
      - openshiftVersion: "{{ version }}"
        version: "{{ version.split('.')[:2] | join('.') }}"
        url: "{{ metalosimage }}" # From mirror_ocp_release
        cpuArchitecture: x86_64
  when:
    - enable_acm | bool
    - dci_disconnected | default(false) | bool

- name: Check for ICSPs that need to be migrated
  community.kubernetes.k8s_info:
    api_version: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
  register: cluster_icsp

- name: "Migrate ICSP to IDMS"
  ansible.builtin.include_tasks: migrate-icsp.yml
  when:
    - cluster_icsp is defined
    - cluster_icsp.resources | length > 0
    - version is version("4.14", ">=")
...
