---
- name: Set EXTERNAL_SUBNET
  ansible.builtin.set_fact:
    extcidrnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
  when:
    - (extcidrnet is not defined or extcidrnet|length < 1)

- name: Get version and build from localhost vars
  ansible.builtin.set_fact:
    version: "{{ hostvars.localhost.version }}"
    build: "{{ hostvars.localhost.build }}"

- name: Get pullsecret from localhost vars
  ansible.builtin.set_fact:
    pullsecret: "{{ hostvars.localhost.dci_pullsecret | to_json }}"
  no_log: true

- name: Remove any previous predefined performance profile
  when:
    - customize_extramanifests_path is defined
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ customize_extramanifests_path }}/20_performance_profile.yml"
    state: absent

- name: Performance profile on install
  when:
    - performance_definition is defined
    - customize_extramanifests_path is defined
    - version is version('4.16', '>=')
  delegate_to: localhost
  block:
    - name: Verify performance profile file exists
      ansible.builtin.stat:
        path: "{{ performance_definition }}"
        get_checksum: false
      register: perf_profile

    - name: Copy performance profile to extra manifests with predefined name
      ansible.builtin.copy:
        src: "{{ performance_definition }}"
        dest: "{{ customize_extramanifests_path }}/20_performance_profile.yml"
        mode: "0644"
      when:
        - perf_profile.stat.exists
...
