---
- name: "Get list of compute and control plane nodes"
  kubernetes.core.k8s_info:
    api: v1
    kind: Node
    label_selectors:
      - "{{ item }}"
  loop:
    - node-role.kubernetes.io/worker
    - node-role.kubernetes.io/master
  register: nodes

- name: "Set Cluster facts"
  vars:
    dci_compute_query: "{{ nodes.results[0] | json_query('resources[*].metadata.name') }}"
    dci_control_plane_query: "{{ nodes.results[1] | json_query('resources[*].metadata.name') }}"
  ansible.builtin.set_fact:
    dci_compute_hosts: "{{ dci_compute_query }}"
    dci_compute_size: "{{ dci_compute_query | length }}"
    dci_control_plane_hosts: "{{ dci_control_plane_query }}"
    dci_control_plane_size: "{{ dci_control_plane_query | length }}"

- name: Get worker MCP status
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: worker
  register: reg_mcpool_worker

- name: Get control-plane MCP status
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: master
  register: reg_mcpool_controlplane
...
