---
- name: "Get specific namespace name for operator: {{ package }}"
  set_fact:
    operator_ns_name: "{{ item.value.required_ns }}"
  loop: "{{ lookup('ansible.builtin.dict', operator_ns, wantlist=True) }}"
  when:
    - package == item.key

- name: "Get operator's package manifests for {{ package }}"
  community.kubernetes.k8s_info:
    api: packages.operators.coreos.com/v1
    kind: PackageManifest
    namespace: default
    name: "{{ package }}"
    label_selectors:
      - "catalog={{ install_all_from_catalog }}"
  register: operator_packagemanifest
  retries: 5
  delay: 3
  no_log: true
  until:
    - operator_packagemanifest.resources is defined
    - operator_packagemanifest.resources | length
    - operator_packagemanifest.resources[0].status is defined
    - operator_packagemanifest.resources[0].status.catalogSource == install_all_from_catalog

- name: "Install the operator {{ package }}"
  include_role:
    name: redhatci.ocp.olm_operator
  vars:
    operator: "{{ package }}"
    source: "{{ install_all_from_catalog }}"
    namespace: "{{ operator_ns_name | default(package, True) }}"
    source_ns: "{{ install_all_from_catalog_source | default('openshift-marketplace') }}"
    operator_group_name: "{{ package }}"
...
