---
- name: Check if IDMS is supported
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: imagedigestmirrorsets.config.openshift.io
  register: idms_res

- name: Copy images or create manifests only for Pre-GA
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_catalog
  vars:
    mc_oc_tool_path: "{{ oc_tool_path }}"
    mc_catalog: "{{ dci_pre_ga_catalog }}"
    mc_registry: "{{ dci_local_registry | default('quay.io', true) }}"
    mc_pullsecret: "{{ dci_pullsecret_file }}"
    mc_is_type: "{{ idms_res.resources is defined and idms_res.resources | length | ternary('idms', 'icsp') }}"
    mc_manifest_only: "{{ not (dci_disconnected | default(false) | bool) }}"
    mc_max_components: 8

- name: Modify Pre-GA Image Sources, except bundles
  vars:
    bundles_exceptions:
      - "cincinnati-operator-metadata-container"
      - "custom-metrics-autoscaler-operator-metadata"
    search_for: "quay.io/prega/test/"
    replacement: "registry.redhat.io/"
  ansible.builtin.shell: >
    sed -i
    -e '/source:/!b;/bundle/b{% for param in bundles_exceptions %};/{{ param }}/b{% endfor %};s,{{ search_for }},{{ replacement }},'
    "{{ mc_is_file.path }}"
  when: mc_is_file is defined
  changed_when: false

- name: "Apply additional IDMS for ODF"
  vars:
    prega_mirror: "{{ dci_disconnected | default(false) | bool |
                ternary (dci_local_registry,
                'quay.io') }}"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'pre-ga-idms.j2') }}"

- name: Append to list of Image Source files
  ansible.builtin.set_fact:
    is_files: "{{ is_files | default([]) + [mc_is_file.path] }}"
  when: mc_is_file is defined

- name: Append the Pre-GA catalog to the list of custom catalogs
  ansible.builtin.set_fact:
    custom_catalogs: "{{ custom_catalogs | default([]) + [mc_catalog_digest] }}"

- name: Get differences between GA and daily Pre-GA
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ dci_cluster_configs_dir }}:/sbin:/usr/sbin:/usr/local/bin/"
  vars:
    ga_version: "{{ dci_pre_ga_catalog | regex_findall(':(v\\d+\\.\\d+)') | first }}"
    ga_index: registry.redhat.io/redhat/redhat-operator-index:{{ ga_version }}
    compare_script: plays/scripts/compare-indexes.sh
  ansible.builtin.shell: >
    set -x;
    {{ compare_script }} {{ ga_index }} {{ dci_pre_ga_catalog }} >
    {{ job_logs.path }}/ga-prega-versions.txt
  register: compare_result
  until: compare_result.rc == 0
  retries: 3
  delay: 10
  delegate_to: localhost
...
