---
- name: "Set catalog facts for disconnected"
  set_fact:
    opm_local_registry_path: "/pruned/redhat-operator-index"
    opm_catalog_source_name: "mirrored-redhat-operators"
    opm_catalog_source_namespace: "openshift-marketplace"
  when:
    - dci_disconnected | default(false) | bool

- name: "Get cluster version"
  community.kubernetes.k8s_info:
    api: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: cluster_version

- name: "Get OCP version"
  vars:
    current_ver_query: "history[?state=='Completed'] | [0].version"
    full_ver: "{{ cluster_version.resources[0].status | json_query(current_ver_query) }}"
    current_ver: "{{ full_ver.split('-')[0] }}"
  ansible.builtin.set_fact:
    ocp_version: "{{ current_ver }}"
    ocp_version_maj: "{{ current_ver.split('.')[0] }}"
    ocp_version_min: "{{ current_ver.split('.')[1] }}"

- name: "Get cluster pull-secret"
  include_tasks: get-cluster-pullsecret.yml

- name: "Create temp directory for docker auths"
  tempfile:
    state: directory
    prefix: dci_auth.
  register: docker_conf

- name: "Copy dci_pull_secret as config.json"
  copy:
    src: "{{ dci_pullsecret_file }}"
    dest: "{{ docker_conf.path }}/config.json"
    mode: "0640"

- name: "Disable default catalog sources for disconnected deployment"
  block:
    - name: "Disable default catalog sources for disconnected deployment"
      community.kubernetes.k8s:
        definition:
          apiVersion: config.openshift.io/v1
          kind: OperatorHub
          metadata:
            name: cluster
          spec:
            disableAllDefaultSources: true

    - name: "Validate default catalogs are disabled"
      vars:
        rh_catalogs: ['certified-operators',
                      'community-operators',
                      'redhat-marketplace',
                      'redhat-operators']
        catalog_names: "{{ catalogs_list.resources | map(attribute='metadata.name') | list }}"
        catalog_inter: "{{ rh_catalogs | intersect(catalog_names) }}"
      community.kubernetes.k8s_info:
        api: operators.coreos.com/v1alpha1
        kind: CatalogSource
        namespace: openshift-marketplace
      register: catalogs_list
      until:
        - catalog_inter | length == 0
      retries: 6
      delay: 10

    - name: Get OLM pod for catalog-operator
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: openshift-operator-lifecycle-manager
        label_selectors:
          - app=catalog-operator
      register: olm_pod

    - name: Restart matching pods
      community.kubernetes.k8s:
        definition: |
          {{ item }}
        state: absent
      loop: "{{ olm_pod.resources }}"

    - name: Wait for OLM pod catalog-operator to be running
      community.kubernetes.k8s_info:
        kind: Pod
        namespace: openshift-operator-lifecycle-manager
        label_selectors:
          - app=catalog-operator
      register: olm_pod
      until: olm_pod | json_query('resources[*].status.phase') | unique == ["Running"]
      retries: 6
      delay: 10
  when:
    - dci_main == 'install'
    - dci_disconnected | default(false) | bool

- name: "Catalog from Image"
  include_tasks:
    file: catalog-from-image.yml
    apply:
      environment:
        DOCKER_CONFIG: "{{ docker_conf.path }}"

- name: "Catalog from File"
  include_tasks:
    file: catalog-from-file.yml
    apply:
      environment:
        DOCKER_CONFIG: "{{ docker_conf.path }}"
  when:
    - operator_catalog_dir | length
    - dci_local_registry | length

- name: "Mirror custom catalogs"
  include_tasks:
    file: mirror-catalog.yml
    apply:
      environment:
        DOCKER_CONFIG: "{{ docker_conf.path }}"
  loop: "{{ custom_catalogs }}"
  loop_control:
    loop_var: catalog
  when:
    - custom_catalogs | default([]) | length

- name: Pre-GA catalog
  include_tasks:
    file: pre-ga-catalog.yml
    apply:
      environment:
        DOCKER_CONFIG: "{{ docker_conf.path }}"
  when:
    - dci_pre_ga_catalog | default('') | length

- name: "Remove docker auths directory"
  file:
    path: "{{ docker_conf.path }}"
    state: absent
  when: docker_conf is defined

- name: "Apply Image Sources for all catalogs"
  block:
    - name: "Apply Image Source manifests"
      community.kubernetes.k8s:
        state: present
        src: "{{ is_file }}"
      loop: "{{ is_files | unique | select | list }}"
      loop_control:
        loop_var: is_file

    - name: "Delete Image Source manifest"
      file:
        path: "{{ is_file }}"
        state: absent
      loop: "{{ is_files | unique | select | list }}"
      loop_control:
        loop_var: is_file
  when:
    - is_files is defined
    - is_files | length

- name: "Wait for updated MCP after applying ICSP"
  include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "MachineConfigPool"
    check_wait_retries: 120
    check_wait_delay: 10
    check_reason: "Apply ICSPs for mirrored catalogs"
    cr_oc: "{{ oc_tool_path }}"

- name: "Clean-up the Image Source list"
  set_fact:
    is_files: []

- name: "Create custom catalog sources"
  include_role:
    name: redhatci.ocp.catalog_source
  vars:
    cs_name: "{{ (((catalog | basename).split(':'))[0]).split('@')[0] }}"
    cs_namespace: "openshift-marketplace"
    cs_image: "{{ catalog }}"
  loop: "{{ custom_catalogs }}"
  loop_control:
    loop_var: catalog
  when:
    - custom_catalogs | default([]) | length

- name: "Override the Red Hat catalog in connected"
  include_role:
    name: redhatci.ocp.catalog_source
  vars:
    cs_name: "redhat-operators"
    cs_namespace: "openshift-marketplace"
    cs_image: "{{ operators_index }}"
    cs_publisher: "Red Hat"
  when:
    - operators_index is defined
    - not dci_disconnected | default(false) | bool
...
