---
- name: Generate SHA-512 crypt hash of the password
  ansible.builtin.command: "openssl passwd -6 '{{ dci_core_user_pass }}'"
  register: hashed_password
  no_log: true

- name: Set directory path for core password extra manifests
  set_fact:
    core_pass_manifests: "{{ customize_extramanifests_path | default ('/tmp/dci_core/' + job_id | default('') ) }}"

- name: Create directory for extra core user manifests
  ansible.builtin.file:
    path: "{{ core_pass_manifests }}"
    state: directory
    mode: '0755'

- name: Set console password for core user >= 4.13
  ansible.builtin.copy:
    content: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: {{ node_role }}
        name: 05-{{ node_role }}-core-password
      spec:
        config:
          ignition:
            version: 3.4.0
          passwd:
            users:
            - name: core
              passwordHash: {{ hashed_password.stdout }}
    dest: "{{ core_pass_manifests }}/05_{{ node_role }}-core-password.yaml"
    mode: "0644"
  loop:
    - worker
    - master
  loop_control:
    loop_var: node_role
  when:
    - version is version('4.13', '>=')

- name: Set console password for core user < 4.13
  vars:
    enc_core_password: "{{ ('core:' + hashed_password.stdout) | b64encode }}"
  ansible.builtin.copy:
    content: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: {{ node_role }}
        name: 20-{{ node_role }}-core-password
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:text/plain;charset=utf-8;base64,{{ enc_core_password }}
              mode: 420
              overwrite: true
              path: /etc/core.passwd
          systemd:
            units:
            - name: set-core-passwd.service
              enabled: true
              contents: |
                [Unit]
                Description=Set 'core' user password for out-of-band login
                [Service]
                Type=oneshot
                ExecStart=/bin/sh -c 'chpasswd -e < /etc/core.passwd'
                [Install]
                WantedBy=multi-user.target
    dest: "{{ core_pass_manifests }}/20_{{ node_role }}-core-password.yaml"
    mode: "0644"
  loop:
    - worker
    - master
  loop_control:
    loop_var: node_role
  when:
    - version is version('4.13', '<')

- name: Prepare manifest for ABI
  when:
    - install_type | default ('ipi') == 'abi'
  block:
    - name: Prepare manifest entries
      set_fact:
        core_password_manifests: >-
          {{
            core_password_manifests | default([]) +
            [{
              'file': core_pass_manifests ~
                      ( '/20_' if version is version('4.13', '<') else '/05_' ) ~
                      node_role ~ '-core-password.yaml'
            }]
          }}
      loop:
        - worker
        - master
      loop_control:
        loop_var: node_role

    - name: Merge with inventory extra_manifests
      set_fact:
        dci_extra_manifests: "{{ extra_manifests | default([]) + core_password_manifests }}"
...
