---
- name: "Mirroring the NFS external storage provisioner image"
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_images
  vars:
    mi_images: ['registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2']
    mi_authfile: "{{ dci_pullsecret_file }}"
    mi_registry: "{{ dci_local_registry }}"
  when:
    - dci_disconnected | default(false) | bool

- name: "Deploy NFS external storage"
  ansible.builtin.include_role:
    name: redhatci.ocp.nfs_external_storage
  vars:
    nes_nfs_server: "{{ nfs_server }}"
    nes_nfs_path: "{{ nfs_path }}"
    nes_path_pattern: "{{ job_id is defined |
                        ternary( job_id+'_${.PVC.namespace}.${.PVC.name}', omit) }}"
    nes_provisioner_image: |-
      {%- if dci_disconnected | default(false) %}
      {{ dci_local_registry }}/sig-storage/nfs-subdir-external-provisioner:{{ nfs_subdir_external_provisioner_tag }}
      {%- else %}
      registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:{{ nfs_subdir_external_provisioner_tag }}
      {%- endif %}
...
