---

- include_tasks: before-install.yml

- name: "installer : SNO Node preparation"
  import_role:
    name: redhatci.ocp.sno_node_prep
  vars:
    sno_pullsecret_file: "{{ hostvars['jumphost']['dci_pullsecret_file'] }}"

- name: "installer : SNO Run IPI installer"
  import_role:
    name: redhatci.ocp.sno_installer
  vars:
    pull_url: "{{ hostvars.jumphost.version_pull_url }}"

- name: "installer : SNO sideload-kernel"
  when:
    - dci_sno_sideload_kernel_uri is defined
    - dci_sno_sideload_kernel_uri | length
  ansible.builtin.import_role:
    name: redhatci.ocp.sideload_kernel
  vars:
    sideload_kernel_uri: "{{ dci_sno_sideload_kernel_uri }}"
    sideload_kernel_base_image: "{{ dci_local_registry | default('registry.access.redhat.com', true) }}/ubi9"
...
