---
- name: "Gathering results for storage service tester"
  include_role:
    name: redhatci.ocp.storage_tester
    tasks_from: gathering-logs.yml
    apply:
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        REGISTRY: "{% if dci_local_registry is defined %}{{ dci_local_registry }}{% else %}registry.redhat.io{% endif %}"
        OC_PATH: "{{ oc_tool_path }}"
  when:
    - dci_main is defined
    - dci_main == 'upgrade'
    - storage_upgrade_tester | default(false) | bool

- name: Upload logs
  include_tasks: get-logs.yml

- name: Delete UEFI boot entries in nodes
  ansible.builtin.include_role:
    name: redhatci.ocp.efi_boot_mgr
  vars:
    ebm_nodes: "{{ dci_compute_hosts + dci_control_plane_hosts }}"
  when: dci_delete_uefi_boot_entries | default(false) | bool
...
