---
- name: "Run the Red Hat Test Suites"
  vars:
    ts_e2e_image: "quay.io/openshift/origin-tests"
    ts_registry: "{{ dci_local_registry }}"
    ts_registry_auth: "{{ dci_pullsecret_file }}"
    ts_ocp_version_maj: "{{ ocp_version_major | int }}"
    ts_ocp_version_min: "{{ ocp_version_minor | int }}"
    ts_registry_certificate: "{{ registry_certificate }}"
    ts_conformance_tests: "{{ dci_openshift_agent_conformance }}"
    ts_configs_dir: "{{ dci_cluster_configs_dir }}"
    ts_csi_tests_dir: "{{ dci_cluster_tests_dir }}"
    ts_csi_test_manifest: "{{ dci_openshift_csi_test_manifest }}"
    ts_do_cni_tests: "{{ dci_do_cni_tests }}"
    ts_do_virt_tests: "{{ dci_do_virt_tests }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.redhat_tests

- name: "Remove origin-tests image"
  containers.podman.podman_image:
    name: "quay.io/openshift/origin-tests"
    state: absent

- name: Run cnf tests
  ansible.builtin.include_tasks: cnf-tests-run.yml
  when:
    - cnf_test_suites is defined
    - cnf_test_suites | length

- name: Run cluster-compare
  vars:
    cc_infra_type: "{{ dci_infra_type | default('core') }}"
    cc_reports_dir: "{{ job_logs.path }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.cluster_compare
  when:
    - dci_cluster_compare | default(false) | bool

- name: Validate ACM policies
  environment:
    KUBECONFIG: "{{ hub_kubeconfig_path }}"
  when:
    - install_type | default('ipi') == 'acm'
    - hub_kubeconfig_path | default('') | length > 0
  block:
    - name: Check if the Policy CRD exists
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: policies.policy.open-cluster-management.io
      register: policy_crd_info
      no_log: true

    - name: Validate ACM policies
      ansible.builtin.include_tasks:
        file: validate-acm-policies.yml
      when: policy_crd_info.resources | length > 0
...
