---
- name: "Setup podman on the jumphost"
  ansible.builtin.include_role:
    name: ansible-role-dci-podman

- name: Get oc version output
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    {{ oc_tool_path }} version
  register: oc_version_str
  delegate_to: localhost

- name: Get OCP version
  ansible.builtin.set_fact:
    ocp_version: "{{ '.'.join(item.split(':')[1].strip().split('.')[0:2]) }}"
    ocp_version_major: "{{ item.split(':')[1].strip().split('.')[0] }}"
    ocp_version_minor: "{{ item.split(':')[1].strip().split('.')[1] }}"
  when: "'Server Version' in item"
  loop: "{{ oc_version_str.stdout_lines }}"

- name: "Run the Red Hat Test Suites"
  vars:
    ts_e2e_image: "quay.io/openshift/origin-tests"
    ts_registry: "{{ dci_local_registry }}"
    ts_registry_auth: "{{ dci_pullsecret_file }}"
    ts_ocp_version_maj: "{{ ocp_version_major | int }}"
    ts_ocp_version_min: "{{ ocp_version_minor | int }}"
    ts_registry_certificate: "{{ registry_certificate }}"
    ts_conformance_tests: "{{ dci_openshift_agent_conformance }}"
    ts_configs_dir: "{{ dci_cluster_configs_dir }}"
    ts_csi_tests_dir: "{{ dci_cluster_tests_dir }}"
    ts_csi_test_manifest: "{{ dci_openshift_csi_test_manifest }}"
    ts_do_cni_tests: "{{ dci_do_cni_tests }}"
    ts_do_virt_tests: "{{ dci_do_virt_tests }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.redhat_tests

- name: "Remove origin-tests image"
  containers.podman.podman_image:
    name: "quay.io/openshift/origin-tests"
    state: absent

- name: Run cnf tests
  ansible.builtin.include_tasks: cnf-tests-run.yml
  when:
    - cnf_test_suites is defined
    - cnf_test_suites | length

- name: Run cluster-compare
  vars:
    cc_infra_type: "{{ dci_infra_type | default('core') }}"
    cc_reports_dir: "{{ job_logs.path }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.cluster_compare
  when:
    - dci_cluster_compare | default(false) | bool
...
