---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: "dci_build_{{ job_id | default('') }}_"
  register: bundle_tmp_dir

- name: "Set working directory"
  ansible.builtin.set_fact:
    bundle_tmp_dir: "{{ bundle_tmp_dir.path }}"

- name: "Clone/update SRIOV network-operator repo"
  vars:
    git_repo: "https://github.com/openshift/sriov-network-operator.git"
    git_ref: "release-{{ base_version }}"
  git:
    version: "{{ git_ref }}"
    repo: "{{ git_repo }}"
    dest: "{{ bundle_tmp_dir }}/sriov-network-operator"
    force: true
  register: sriov_clone
  retries: 3
  delay: 10
  until: not sriov_clone.failed

- name: "Add expire label to SRIOV bundle image"
  ansible.builtin.lineinfile:
    path: "{{ bundle_tmp_dir }}/sriov-network-operator/bundleci.Dockerfile"
    line: "LABEL maintainer='Telco DCI team' quay.expires-after=5h"
    insertafter: EOF

- name: "Pin CSV"
  ansible.builtin.script:
    cmd: >
      plays/scripts/use-digest
      {{ bundle_tmp_dir }}/sriov-network-operator/manifests/stable/sriov-network-operator.clusterserviceversion.yaml

- name: "Build SRIOV bundle image"
  ansible.builtin.shell: >
    podman build .
    -f bundleci.Dockerfile
    --no-cache
    -t {{ sriov_bundle }}:{{ base_version }}
  args:
    chdir: "{{ bundle_tmp_dir }}/sriov-network-operator"

- name: "Push the new bundle image to registry"
  ansible.builtin.shell:
    cmd: >
      podman push
      --authfile {{ dci_pullsecret_file }}
      {{ sriov_bundle }}:{{ base_version }}
  register: cat_push
  retries: 3
  delay: 10
  until: cat_push.rc == 0

- name: "Get bundle image SHA256"
  ansible.builtin.shell:
    cmd: >
      set -o pipefail;
      skopeo inspect
      --authfile {{ dci_pullsecret_file }}
      docker://{{ sriov_bundle }}:{{ base_version }} |
      jq -r '.Digest'
  register: bundle_sha
  retries: 5
  delay: 5
  until:
    - bundle_sha.stdout | regex_search('^sha')

- name: "Delete temp directory"
  ansible.builtin.file:
    state: absent
    path: "{{ bundle_tmp_dir }}"

- name: Add the sriov bundle to the list of upstream bundles
  ansible.builtin.set_fact:
    upstream_bundles: "{{ upstream_bundles | default([]) + [sriov_bundle + '@' + bundle_sha.stdout] }}"

- name: Remove local bundle image
  ansible.builtin.shell:
    cmd: >
      podman rmi -f
      {{ sriov_bundle }}:{{ base_version }}

- name: Set upstream sriov variable
  ansible.builtin.set_fact:
    upstream_sriov: true
