---
- name: Create cluster
  hosts: bastion
  gather_facts: false
  vars:
    pull_secret: "{{ hostvars['localhost']['pull_secret'] }}"
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create cluster
      block:
        - name: "Create cluster"
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.create_cluster
      rescue:
        - name: Teardown failure
          include_tasks: teardown_failure.yml
...
