---
- name: Play to populate image_hashes for relevant images
  hosts: localhost
  vars:
    destination_hosts:
      - assisted_installer
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Populate image hashes
      block:
        - name: Pre-compute need to get hashes
          set_fact:
            run_get_hash: "{{ image_hashes | default({}) | length == 0  }}"

        - name: Get image hash
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.get_image_hash
          when: run_get_hash
      rescue:
        - name: Teardown error
          include_tasks: teardown_error.yml

- name: Deploy OpenShift Assisted Installer On Prem
  hosts: assisted_installer
  vars:
    pull_secret: "{{ hostvars['localhost']['pull_secret'] }}"
    _setup_assisted_installer: "{{ setup_assisted_installer | default(True) }}"
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Deploy Assisted Installer on-prem
      when: _setup_assisted_installer == True
      block:
        - name: Setup assisted installer
          include_role:
            name: redhatci.ocp.setup_assisted_installer
        - name: Wait for up to 60 minutes for the assisted installer to come online
          uri:
            url: "http://{{ ansible_host }}:8090/ready"
            method: GET
            status_code: [200, 201]
          register: result
          until: result is succeeded
          retries: 120
          delay: 30
          delegate_to: bastion
        - name: Wait for up to 60 minutes for the assisted installer image service to come online
          uri:
            url: "http://{{ ansible_host }}:8888/health"
            method: GET
            status_code: [200, 201]
          register: result
          until: result is succeeded
          retries: 120
          delay: 30
          delegate_to: bastion
      rescue:
        - name: Teardown error
          include_tasks: teardown_error.yml
...
