---
- name: Extract openshift installer
  hosts: bastion
  gather_facts: false
  environment:
    PATH: "{{ dci_cluster_configs_dir }}:{{ ansible_env.PATH }}"
  vars:
    destination_hosts:
      - bastion
    pull_secret: "{{ hostvars['localhost']['pull_secret'] }}"
    extract_dest_path: "{{ dci_cluster_configs_dir }}/extract"
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Extract installer
      block:
        - name: "Pre-compute need to get hashes"
          set_fact:
            run_get_hash: "{{ assisted_installer_release_images | default({}) | length == 0  }}"
        - name: "Get image hash"
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.get_image_hash
          when: run_get_hash | bool
        - name: "Extract openshift installer"
          include_role:
            name: redhatci.ocp.extract_openshift_installer
      rescue:
        - name: Teardown failures
          include_tasks: teardown_failure.yml
...
