---
- name: Generate manfiests for agent_based_installer
  hosts: bastion
  vars:
    destination_hosts:
      - bastion
    pull_secret: "{{ hostvars['localhost']['pull_secret'] }}"
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Generate manifest for Agent Based installer
      block:
        - name: Pre-compute need to get hashes
          ansible.builtin.set_fact:
            run_get_hash: "{{ assisted_installer_release_images | default({}) | length == 0 }}"
        - name: "Get_image_hash"
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.get_image_hash
          when: run_get_hash
        - name: "Generate_manifests"
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.generate_manifests
      rescue:
        - name: Teardown failure
          include_tasks: teardown_failure.yml
...
