---
- name: Monitor install process of agent_based_installer
  hosts: bastion
  gather_facts: false
  vars_files:
    - ../../group_vars/all
  tasks:
    - block:
        - name: "assisted installer: monitor agent based installer"
          vars:
            repo_root_path: "{{ dci_cluster_configs_dir }}"
          include_role:
            name: redhatci.ocp.monitor_agent_based_installer
      rescue:
        - include_tasks: teardown_failure.yml
...
