---
- name: Up bootstrap VM
  hosts: vm_host
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
    hook_action: install
  tasks:
    - set_fact:
        resources: "{{ resources|default([])|union([item.name]) }}"
      with_items:
        - "{{ hosts }}"
    - include_role:
        name: ocp-on-libvirt
